import { injectGlobal } from "@emotion/css";

import type { Style, UiTokens } from "./api.ts";
import { FALLBACK_THEME, themeVariables } from "./theme.ts";

export function installFoundation(tokens: UiTokens): void {
  injectGlobal(foundation(tokens) as Parameters<typeof injectGlobal>[number]);
}

function foundation(tokens: UiTokens): Style {
  return {
    ":root": {
      color: "var(--text)",
      background: "var(--background)",
      fontFamily: 'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      fontSize: tokens.font.body,
      fontSynthesis: "none",
      ...themeVariables(FALLBACK_THEME.dark!),
      "--content-width": `${tokens.layout.content}px`,
      "--copy-width": `${tokens.layout.copy}px`,
      "--window-controls-width": `${tokens.size.header * 3}px`,
      "--window-action-inset": `${tokens.space.medium}px`,
      "--space-compact": `${tokens.space.compact}px`,
      "--space-small": `${tokens.space.small}px`,
      "--space-medium": `${tokens.space.medium}px`,
      "--space-large": `${tokens.space.large}px`,
      "--space-section": `${tokens.space.section}px`,
      "--space-content": `${tokens.space.content}px`,
      "--space-page": `${tokens.space.page}px`,
      "--indicator-size": `${tokens.size.indicator}px`,
      "--icon-tiny": `${tokens.size.iconTiny}px`,
      "--icon-size": `${tokens.size.icon}px`,
      "--control-tiny": `${tokens.size.controlTiny}px`,
      "--control-compact": `${tokens.size.controlCompact}px`,
      "--control-height": `${tokens.size.control}px`,
      "--control-large": `${tokens.size.controlLarge}px`,
      "--header-height": `${tokens.size.header}px`,
      "--header-large": `${tokens.size.headerLarge}px`,
      "--setting-height": `${tokens.size.setting}px`,
      "--layout-actions-width": "0px",
      "--radius-compact": `${tokens.radius.compact}px`,
      "--control-radius": `${tokens.radius.control}px`,
      "--row-radius": `${tokens.radius.row}px`,
      "--surface-radius": `${tokens.radius.surface}px`,
      "--dialog-radius": `${tokens.radius.dialog}px`,
      "--radius-round": `${tokens.radius.round}px`,
      "--font-caption": `${tokens.font.caption}px`,
      "--font-small": `${tokens.font.small}px`,
      "--font-label": `${tokens.font.label}px`,
      "--font-body": `${tokens.font.body}px`,
      "--font-content": `${tokens.font.content}px`,
      "--font-title": `${tokens.font.title}px`,
      "--weight-medium": tokens.weight.medium,
      "--weight-semibold": tokens.weight.semibold,
      "--weight-bold": tokens.weight.bold,
      "--line-body": tokens.line.body,
      "--line-content": tokens.line.content,
      "--tracking-wide": ".05em",
      "--tracking-tight": "-.03em",
      "--z-resizer": 8,
      "--z-chrome": 10,
      "--z-popover": 30,
      "--z-preview": 40,
      "--z-menu": 50,
      "--z-modal": 80,
      "--z-notice": 90,
      "--z-window": 100,
      "--mono": '"Cascadia Code", "SFMono-Regular", Consolas, monospace',
    },
    "*": {
      boxSizing: "border-box",
      scrollbarWidth: "thin",
      scrollbarColor: "var(--border) transparent",
    },
    "[hidden]": { display: "none !important" },
    "html, body, #app": { width: "100%", height: "100%", margin: 0, overflow: "hidden" },
    body: { background: "var(--background)", color: "var(--text)" },
    "body.resizing, body.resizing *": {
      cursor: "col-resize !important",
      userSelect: "none !important",
    },
    "body.resizing-terminal, body.resizing-terminal *": {
      cursor: "row-resize !important",
      userSelect: "none !important",
    },
    "button, input, textarea, select": { color: "inherit", font: "inherit" },
    button: {
      "--button-icon-size": "var(--icon-size)",
      padding: 0,
      border: 0,
      background: "transparent",
    },
    "button > .vrui-icon": {
      width: "var(--button-icon-size)",
      minWidth: "var(--button-icon-size)",
      maxWidth: "var(--button-icon-size)",
      height: "var(--button-icon-size)",
      minHeight: "var(--button-icon-size)",
      maxHeight: "var(--button-icon-size)",
    },
    "button > .vrui-icon > svg": {
      width: "100%",
      minWidth: "100%",
      maxWidth: "100%",
      height: "100%",
      minHeight: "100%",
      maxHeight: "100%",
      flex: "none",
    },
    ":focus, :focus-visible": { outline: 0 },
    "button:disabled": { cursor: "not-allowed", opacity: 0.45 },
    ".vrui-icon": {
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      flex: "none",
      lineHeight: 0,
    },
    ".vrui-icon > svg, .provider-mark": { display: "block", flex: "none" },
    ".provider-icon": {
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      flex: "none",
      color: "var(--text)",
      lineHeight: 0,
    },
    ".provider-mark": { fill: "currentColor" },
    "*::-webkit-scrollbar": { width: tokens.space.medium, height: tokens.space.medium },
    "*::-webkit-scrollbar-button": { display: "none", width: 0, height: 0 },
    "*::-webkit-scrollbar-track, *::-webkit-scrollbar-corner": { background: "transparent" },
    "*::-webkit-scrollbar-thumb": {
      minWidth: tokens.size.control,
      minHeight: tokens.size.control,
      border: "1px solid transparent",
      borderRadius: tokens.radius.round,
      background: "var(--border)",
      backgroundClip: "padding-box",
    },
    "*::-webkit-scrollbar-thumb:hover": {
      background: "var(--muted)",
      backgroundClip: "padding-box",
    },
  };
}
