export { expandHome, sandHome } from './paths/home'
export { projectFolder } from './paths/project'
export { isQuietFolder, nearestRoot, samePath } from './paths/roots'
export { parseProject, parseProjectsFile, projectsPath, readProjectsFile, writeProjectsFile } from './projects/file'
export { copyPath, localCopies, localProjects, projectOfFolder, type LocalCopy, type LocalProjects } from './projects/local'
export { watchProjects } from './projects/watch'
export { scratchFolder, scratchRoot } from './paths/scratch'
export { watchedFolders, type WatchedFolders } from './watch/folders'
export { parseFrontmatter } from './frontmatter/parse'
export { debouncedWatch, type WatchOptions } from './watch/debounced'
export { jsonListStore, type JsonListStore } from './store/json-list'
export { environment, toolNotes } from './instructions/environment'
export { projectInstructions } from './instructions/project'
export { scanFolder } from './files/scan'
export { folderEntries } from './files/entries'
export { replaceFile } from './files/replace'
