export const help = [
  'usage: sand [-c | -r <id>] [--lan]     start sand in the background if needed and open it in the browser',
  '       sand serve [--lan]              run sand in the foreground',
  '       sand stop                       stop the background sand',
  '       sand -p "<prompt>" [-c | -r <id>] [--cwd <folder>] [--model <name>] [--effort <level>] [--fast]',
  '                                       test runner: run one prompt or /command without a server and print the reply',
  '       sand devices [--lan]            show a link and QR code to open sand on your phone',
  '       sand remote [add <link> | remove <pc>]   list, pair or forget other PCs running sand',
  '       sand project [list] [--all]     list projects on this PC and every online paired PC',
  '       sand project add <path> | remove <name|path> [--on <pc>] | rename <name> <new name> | hide <name> | show <name>',
  '       sand project root [path] [--on <pc>]    print or set the folder new projects go in',
  '       sand project copy <name> --to <pc> [--from <pc>] [--path <folder>] [--setup]   put a project on another PC',
  '       sand project sync <name> --from <pc> --to <pc>   send the newest work, merging if both changed',
  '       sand project status <name>      compare the copies of a project across PCs',
  '       sand project resolve <name> --on <pc> (--ours | --theirs) [file…]   settle merge conflicts',
  '       sand usage [24h | 7d | 30d | 90d]       tokens, API cost and plan limits (default 30d)',
  '',
  '  -c          open the most recent thread in this folder',
  '  -r <id>     open the thread with this id',
  '  --fast      fast mode on models that have it: quicker replies at a higher price',
  '  --lan       listen on every network address so phones and other computers can connect;',
  '              an already running sand starts sharing too, until it restarts',
  '  --on <pc>   the paired PC a project command acts on',
  '  --from <pc> --to <pc>   the PCs a project is copied or synced between ("this" is the PC you are on)',
  '  --path <dir>            where copy puts the project (default: the project folder of the target PC)',
  '  --setup                 run the project setup command (install dependencies) after copy',
  '  --all                   include hidden projects in the list',
  '  --ours | --theirs       keep the receiving PC version or the incoming one when resolving',
  '  --cwd <dir> the folder to work in',
].join('\n')
