export const help = [
  'usage: sand [-c | -r <id>]             start sand in the background if needed and open it in the browser,',
  '                                       already paired so it needs no link or QR code',
  '       sand serve                      run sand in the foreground (it restarts plugins without dropping the page)',
  '       sand stop                       stop the background sand',
  '       sand -p "<prompt>" [-c | -r <id>] [--home <folder>] [--cwd <folder>] [--model <name>] [--effort <level>] [--fast]',
  '                                       test runner: run one prompt or /command without a server and print the reply',
  '       sand devices                    list paired devices and show a one-time QR code and link to pair a phone',
  '       sand devices remove <name>      unpair a device; it has to pair again to use sand',
  '       sand devices lan [on | off]     show or change whether sand listens on the home network (on by default)',
  '       sand remote [add <pairing link> | remove <pc>]   list, pair or forget other PCs running sand;',
  '                                       the pairing link comes from Devices (or `sand devices`) on the other PC',
  '       sand project [list] [--all]     list projects and their copies on every PC, with git remote and missing folders',
  '       sand project add <path> | rename <name> <new name> | hide <name> | show <name>',
  '       sand project remove <name|path> [--on <pc>]   delete the project on every PC, or with --on forget that PC copy;',
  '                                       folders stay on disk',
  '       sand project root [path] [--on <pc>]    print or set the folder new projects go in',
  '       sand project copy <name> --to <pc> [--from <pc>] [--path <folder>] [--setup]   put a copy of a project on another PC',
  '       sand project sync <name> --from <pc> --to <pc>   send the newest work, merging if both changed',
  '       sand project status <name>      compare the copies of a project across PCs',
  '       sand project resolve <name> --on <pc> (--ours | --theirs) [file…]   settle merge conflicts',
  '       sand usage [24h | 7d | 30d | 90d]       tokens, API cost and plan limits (default 30d)',
  '',
  '  -c          open the most recent thread',
  '  -r <id>     open the thread with this id',
  '  --fast      fast mode on models that have it: quicker replies at a higher price',
  '  --on <pc>   the PC a project command acts on',
  '  --from <pc> --to <pc>   the PCs a project is copied or synced between ("this" is the PC you are on)',
  '  --path <dir>            where copy puts the project (default: the project folder of the target PC)',
  '  --setup                 run the project setup command (install dependencies) after copy',
  '  --all                   include hidden projects in the list',
  '  --ours | --theirs       keep the receiving PC version or the incoming one when resolving',
  '  --cwd <dir>             the folder a -p thread works in',
  '  --home <dir>            keep threads and settings in this folder instead of ~/.sand, e.g. for tests (or set SAND_HOME);',
  '                          it borrows ~/.sand/sand.toml and ~/.sand/auth.json until it has its own',
].join('\n')
