import { icon as lucideIcon, type IconNode } from '@vaakx-dev/vrui'
import {
  ArrowDown,
  ArrowLeft,
  ArrowUp,
  Bot,
  ChartColumn,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleDashed,
  CircleHelp,
  Clock,
  Command,
  Copy,
  CopyPlus,
  CornerDownRight,
  CornerUpRight,
  Ellipsis,
  Eye,
  File,
  FilePlus,
  FileText,
  Folder,
  FolderGit2,
  FolderPlus,
  GitBranch,
  GitCompare,
  GitFork,
  Gauge,
  Goal,
  GripVertical,
  Hourglass,
  Info,
  Laptop,
  Layers,
  Link,
  ListOrdered,
  ListPlus,
  ListTree,
  LoaderCircle,
  Lock,
  Menu,
  MessageSquare,
  Minimize2,
  Monitor,
  PanelLeft,
  PanelRight,
  Paperclip,
  Pencil,
  Pin,
  Plus,
  Puzzle,
  RefreshCw,
  RotateCcw,
  Search,
  Settings,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  Square,
  SquarePen,
  SquareSlash,
  SquareTerminal,
  Tag,
  TrendingDown,
  TrendingUp,
  TextSearch,
  Workflow,
  Wrench,
  X,
  Zap,
} from 'lucide'

const nodes: Record<string, IconNode> = {
  search: Search,
  compose: SquarePen,
  folder: Folder,
  down: ChevronDown,
  left: ChevronLeft,
  right: ChevronRight,
  pin: Pin,
  branch: GitBranch,
  sidebar: PanelLeft,
  panel: PanelRight,
  menu: Menu,
  up: ArrowUp,
  plus: Plus,
  x: X,
  file: File,
  check: Check,
  term: SquareTerminal,
  pencil: Pencil,
  eye: Eye,
  bot: Bot,
  tree: ListTree,
  command: Command,
  message: MessageSquare,
  puzzle: Puzzle,
  help: CircleHelp,
  grep: TextSearch,
  stop: Square,
  layers: Layers,
  gear: Settings,
  loader: LoaderCircle,
  working: CircleDashed,
  arrowDown: ArrowDown,
  copy: Copy,
  alert: CircleAlert,
  back: ArrowLeft,
  compare: GitCompare,
  'file-plus': FilePlus,
  'file-text': FileText,
  fork: GitFork,
  logo: Hourglass,
  smartphone: Smartphone,
  sparkles: Sparkles,
  tag: Tag,
  workflow: Workflow,
  wrench: Wrench,
  duplicate: CopyPlus,
  paperclip: Paperclip,
  slash: SquareSlash,
  queue: ListPlus,
  steer: CornerDownRight,
  promote: CornerUpRight,
  grip: GripVertical,
  queued: ListOrdered,
  more: Ellipsis,
  retry: RotateCcw,
  reload: RefreshCw,
  compact: Minimize2,
  zap: Zap,
  clock: Clock,
  sliders: SlidersHorizontal,
  info: Info,
  laptop: Laptop,
  monitor: Monitor,
  link: Link,
  'folder-plus': FolderPlus,
  'folder-git': FolderGit2,
  chart: ChartColumn,
  lock: Lock,
  goal: Goal,
  gauge: Gauge,
  'trend-up': TrendingUp,
  'trend-down': TrendingDown,
}

const iconNames = () => Object.keys(nodes)

const missing = new Set<string>()

const known = (name: string) => {
  const node = nodes[name]
  if (!node && !missing.has(name)) {
    missing.add(name)
    console.warn(`Unknown icon "${name}"; known icons: ${iconNames().join(', ')}`)
  }
  return node ?? CircleHelp
}

export const icon = (name: string, size = 16) => lucideIcon(known(name), size, 1.8)
